# Generated by Django 5.2.1 on 2025-05-17 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("schools", "0004_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="schools.school",
            ),
        ),
        migrations.DeleteModel(
            name="School",
        ),
    ]
