# Generated by Django 5.2.1 on 2025-05-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="school",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
